### PR TITLE
import Control.Monad.Fail to fix GHC 8.6 build

### PR DESCRIPTION
**Pull request by robx**
The package was failing to build on GHC 8.6:

```
/s/holmes/src/Control/Monad/Holmes.hs:62:10: error:
    Not in scope: type constructor or class ‘MonadFail’
   |        
62 | instance MonadFail Holmes where
   |          ^^^^^^^^^
```

Or see https://matrix.hackage.haskell.org/#/package/holmes.

I've checked that it builds with both GHC 8.6 and GHC 8.8 with this change; unfortunately it causes warnings on GHC 8.8 that I don't know how to avoid:

```
/s/holmes/src/Control/Monad/Watson.hs:33:1: warning: [-Wunused-imports]
    The import of ‘Control.Monad.Fail’ is redundant
      except perhaps to import instances from ‘Control.Monad.Fail’
    To import instances alone, use: import Control.Monad.Fail()
   |        
33 | import Control.Monad.Fail (MonadFail (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by i-am-tom** [comment]
Damn breaking changes... It might be time to whip out a small amount of {- CPP -}, much as I hate to do so. Are you happy to do so? I don't mind either way - happy to accept the PR and then add the pragmas :)

**Comment by robx** [comment]
I'd happily leave that to you. :)

(This should also fix hackage haddock builds by the way.)

**Comment by i-am-tom** [comment]
Fixed in #9!
